name: "Install Dependencies"
description: "Install METIS and MUMPS with caching"

runs:
  using: "composite"
  steps:
    - name: Install gfortran
      shell: bash
      run: |
        apt-get -qq -y install gfortran
    - name: Cache METIS
      id: cache-metis
      uses: actions/cache@v5
      with:
        path: METIS/install
        key: metis-v5.1.0.4-${{ runner.os }}
    - name: Install METIS
      shell: bash
      if: steps.cache-metis.outputs.cache-hit != 'true'
      run: |
        git clone -b v5.1.0.4 https://github.com/scivision/METIS.git
        cd METIS
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build
    - name: Set METIS environment variables
      shell: bash
      run: |
        echo "METIS_DIR=$GITHUB_WORKSPACE/METIS/install" >> $GITHUB_ENV
        echo "METIS_ROOT=$GITHUB_WORKSPACE/METIS/install" >> $GITHUB_ENV
    - name: Cache MUMPS
      id: cache-mumps
      uses: actions/cache@v5
      with:
        path: mumps/install
        key: mumps-v5.5.1.11-metis-${{ runner.os }}
    - name: Install MUMPS
      shell: bash
      if: steps.cache-mumps.outputs.cache-hit != 'true'
      run: |
        git clone -b v5.5.1.11 https://github.com/scivision/mumps.git
        cd mumps
        cmake -Bbuild -DBUILD_SINGLE=on -DBUILD_DOUBLE=on -Dmetis=on -Dopenmp=on -Dparallel=off -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_BUILD_TYPE=Release -S .
        cmake --build build
        cmake --install build
    - name: Set MUMPS environment variables
      shell: bash
      run: |
        echo "MUMPS_DIR=$GITHUB_WORKSPACE/mumps/install" >> $GITHUB_ENV
